**4.1 Exercise on Functions:**

**Task 1:**

Create a Python program that converts between different units of measurement.

In [1]:
def convert_length(value, unit):

    if unit == 'm':
        return value * 3.28084  # 1 meter = 3.28084 feet
    elif unit == 'ft':
        return value / 3.28084  # 1 foot = 0.3048 meters
    else:
        raise ValueError("Unsupported length unit")

def convert_weight(value, unit):

    if unit == 'kg':
        return value * 2.20462  # 1 kg = 2.20462 lbs
    elif unit == 'lbs':
        return value / 2.20462  # 1 lb = 0.453592 kg
    else:
        raise ValueError("Unsupported weight unit")

def convert_volume(value, unit):

    if unit == 'L':
        return value * 0.264172  # 1 liter = 0.264172 gallons
    elif unit == 'gal':
        return value / 0.264172  # 1 gallon = 3.78541 liters
    else:
        raise ValueError("Unsupported volume unit")

print("Unit Converter: Length, Weight, Volume")
print("1. Length (meters <-> feet)")
print("2. Weight (kilograms <-> pounds)")
print("3. Volume (liters <-> gallons)")

try:
    choice = int(input("Choose conversion type (1-3): "))
    value = float(input("Enter the value to convert: "))

    if choice == 1:
        unit = input("Enter unit (m for meters, ft for feet): ").strip().lower()
        converted = convert_length(value, unit)
        print(f"Converted value: {converted:.4f}")
    elif choice == 2:
        unit = input("Enter unit (kg for kilograms, lbs for pounds): ").strip().lower()
        converted = convert_weight(value, unit)
        print(f"Converted value: {converted:.4f}")
    elif choice == 3:
        unit = input("Enter unit (L for liters, gal for gallons): ").strip().lower()
        converted = convert_volume(value, unit)
        print(f"Converted value: {converted:.4f}")
    else:
        print("Invalid choice. Please select a valid option.")
except ValueError as e:
    print(f"Error: {e}. Please enter a valid number and unit.")


Unit Converter: Length, Weight, Volume
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)
Choose conversion type (1-3): 2
Enter the value to convert: 20
Enter unit (kg for kilograms, lbs for pounds): kg
Converted value: 44.0924


**Task - 2:**

Create a Python program that performs various mathematical operations on a list of numbers.

In [2]:
def calculate_sum(numbers):

    return sum(numbers)

def calculate_average(numbers):

    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):

    return max(numbers)

def find_minimum(numbers):

    return min(numbers)

print("Mathematical Operations: Sum, Average, Maximum, Minimum")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

try:
    choice = int(input("Choose an operation (1-4): "))
    numbers = list(map(float, input("Enter a list of numbers separated by spaces: ").split()))

    if not numbers:
        raise ValueError("The list of numbers cannot be empty.")

    if choice == 1:
        result = calculate_sum(numbers)
    elif choice == 2:
        result = calculate_average(numbers)
    elif choice == 3:
        result = find_maximum(numbers)
    elif choice == 4:
        result = find_minimum(numbers)
    else:
        print("Invalid choice. Please select a valid option.")
        exit()

    print(f"Result: {result}")
except ValueError as e:
    print(f"Error: {e}. Please enter a valid input.")


Mathematical Operations: Sum, Average, Maximum, Minimum
1. Sum
2. Average
3. Maximum
4. Minimum
Choose an operation (1-4): 2
Enter a list of numbers separated by spaces: 3 4 5 7 9 2
Result: 5.0


**4.2 Exercise on List Manipulation:**

**1. Extract Every Other Element:**

Write a Python function that extracts every other element from a list, starting from the first element.

In [3]:
def extract_every_other(lst):

    return lst[::2]


data = [1, 2, 3, 4, 5, 6]
result = extract_every_other(data)
print(result)

[1, 3, 5]


**2. Slice a Sublist:**

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

In [4]:
def get_sublist(lst, start, end):

    return lst[start:end+1]

data = [1, 2, 3, 4, 5, 6]
result = get_sublist(data, 2, 4)
print(result)


[3, 4, 5]


**3. Reverse a List Using Slicing:**

Write a Python function that reverses a list using slicing.

In [5]:
def reverse_list(lst):

    return lst[::-1]

data = [1, 2, 3, 4, 5]
result = reverse_list(data)
print(result)

[5, 4, 3, 2, 1]


**4. Remove the First and Last Elements:**

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

In [6]:
def remove_first_last(lst):

    return lst[1:-1]

data = [1, 2, 3, 4, 5]
result = remove_first_last(data)
print(result)

[2, 3, 4]


**5. Get the First n Elements:**

Write a Python function that extracts the first n elements from a list.

In [7]:
def get_first_n(lst, n):

    return lst[:n]

data = [1, 2, 3, 4, 5]
result = get_first_n(data, 3)
print(result)

[1, 2, 3]


**6. Extract Elements from the End:**

Write a Python function that extracts the last n elements of a list using slicing.

In [8]:
def get_last_n(lst, n):
    return lst[-n:]

data = [1, 2, 3, 4, 5]
result = get_last_n(data, 2)
print(result)

[4, 5]


**7. Extract Elements in Reverse Order:**

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

In [9]:
def reverse_skip(lst):
    return lst[-2::-2]

input_list = [1, 2, 3, 4, 5, 6]
output_list = reverse_skip(input_list)
print(output_list)


[5, 3, 1]


**4.3 Exercise on Nested List:**

**1. Flatten a Nested List:**

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

In [10]:
def flatten(lst):
    return [item for sublist in lst for item in sublist]

input_list = [[1, 2], [3, 4], [5]]
output_list = flatten(input_list)
print(output_list)


[1, 2, 3, 4, 5]


**2. Accessing Nested List Elements:**

Write a Python function that extracts a specific element from a nested list given its indices.

In [11]:
def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst

input_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
output = access_nested_element(input_list, indices)
print(output)


6


**3. Sum of All Elements in a Nested List:**

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [12]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

input_list = [[1, 2], [3, [4, 5]], 6]
output = sum_nested(input_list)
print(output)


21


**4. Remove Specific Element from a Nested List:**

In [13]:
def remove_element(lst, elem):
    for i in range(len(lst)):
        if isinstance(lst[i], list):
            lst[i] = remove_element(lst[i], elem)
        else:
            if lst[i] == elem:
                lst.pop(i)
                return remove_element(lst, elem)  # To recheck after removal
    return lst

input_list = [[1, 2], [3, 2], [4, 5]]
elem = 2
output = remove_element(input_list, elem)
print(output)


[[1], [3], [4, 5]]


**5. Find the Maximum Element in a Nested List:**

Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [14]:
def find_max(lst):
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

input_list = [[1, 2], [3, [4, 5]], 6]
output = find_max(input_list)
print(output)


6


**6. Count Occurrences of an Element in a Nested List:**

Write a Python function that counts how many times a specific element appears in a nested list.

In [15]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count

input_list = [[1, 2], [2, 3], [2, 4]]
elem = 2
output = count_occurrences(input_list, elem)
print(output)


3


**7. Flatten a List of Lists of Lists:**

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [16]:
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

input_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
output = deep_flatten(input_list)
print(output)


[1, 2, 3, 4, 5, 6, 7, 8]


**8. Nested List Average:**

Write a Python function that calculates the average of all elements in a nested list.

In [17]:
def average_nested(lst):
    total = 0
    count = 0
    def flatten_and_count(lst):
        nonlocal total, count
        for item in lst:
            if isinstance(item, list):
                flatten_and_count(item)
            else:
                total += item
                count += 1
    flatten_and_count(lst)
    return total / count if count > 0 else 0

input_list = [[1, 2], [3, 4], [5, 6]]
output = average_nested(input_list)
print(output)


3.5


**10 To - Do - NumPy**

**10.1 Basic Vector and Matrix Operation with Numpy.**

**Problem - 1: Array Creation:**

1. Initialize an empty array with size 2X2.

In [18]:
import numpy as np

empty_array = np.empty((2, 2))
print(empty_array)


[[2.49695185e-316 0.00000000e+000]
 [2.33419537e-312 1.62374675e-319]]


2. Initialize an all one array with size 4X2.

In [19]:
import numpy as np

ones_array = np.ones((4, 2))
print(ones_array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [21]:
import numpy as np

filled_array = np.full((3, 3), 1)
print(filled_array)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [22]:
import numpy as np

array = np.array([[1, 2], [3, 4]])
zeros_array = np.zeros_like(array)
print(zeros_array)


[[0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [23]:
import numpy as np

array = np.array([[1, 2], [3, 4]])
ones_array = np.ones_like(array)
print(ones_array)


[[1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [24]:
import numpy as np

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(numpy_array)


[1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [25]:
import numpy as np

array = np.arange(10, 50)
print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [26]:
import numpy as np

matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [27]:
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [28]:
import numpy as np

random_array = np.random.random(30)
mean_value = random_array.mean()
print(mean_value)


0.499624880624343


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [29]:
import numpy as np

random_array = np.random.random((10, 10))
min_value = random_array.min()
max_value = random_array.max()
print("Minimum value:", min_value)
print("Maximum value:", max_value)


Minimum value: 0.017507074550964563
Maximum value: 0.9843249282162617


6. Create a zero array of size 10 and replace 5th element with 1.

In [30]:
import numpy as np

zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [31]:
import numpy as np

arr = [1, 2, 0, 0, 4, 0]
reversed_arr = np.array(arr)[::-1]
print(reversed_arr)


[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [32]:
import numpy as np

array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [33]:
import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Problem - 3: Array Operations:**

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

1. Add the two array.

In [35]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

result_xy = x + y
result_vw = v + w

print("Sum of x and y:")
print(result_xy)

print("Sum of v and w:")
print(result_vw)


Sum of x and y:
[[ 6  8]
 [10 13]]
Sum of v and w:
[20 22]


2. Subtract the two array.

In [36]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

result_xy_sub = x - y
result_vw_sub = v - w

print("Difference of x and y:")
print(result_xy_sub)

print("Difference of v and w:")
print(result_vw_sub)


Difference of x and y:
[[-4 -4]
 [-4 -3]]
Difference of v and w:
[-2 -2]


3. Multiply the array with any integers of your choice.

In [38]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

multiplier = 3

result_x_mult = x * multiplier
result_y_mult = y * multiplier
result_v_mult = v * multiplier
result_w_mult = w * multiplier

print("Multiplication of x with 3:")
print(result_x_mult)

print("Multiplication of y with 3:")
print(result_y_mult)

print("Multiplication of v with 3:")
print(result_v_mult)

print("Multiplication of w with 3:")
print(result_w_mult)


Multiplication of x with 3:
[[ 3  6]
 [ 9 15]]
Multiplication of y with 3:
[[15 18]
 [21 24]]
Multiplication of v with 3:
[27 30]
Multiplication of w with 3:
[33 36]


4. Find the square of each element of the array.

In [39]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

result_x_square = np.square(x)
result_y_square = np.square(y)
result_v_square = np.square(v)
result_w_square = np.square(w)

print("Square of each element in x:")
print(result_x_square)

print("Square of each element in y:")
print(result_y_square)

print("Square of each element in v:")
print(result_v_square)

print("Square of each element in w:")
print(result_w_square)


Square of each element in x:
[[ 1  4]
 [ 9 25]]
Square of each element in y:
[[25 36]
 [49 64]]
Square of each element in v:
[ 81 100]
Square of each element in w:
[121 144]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [40]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("Dot product of v and w:")
print(dot_vw)

print("Dot product of x and v:")
print(dot_xv)

print("Dot product of x and y:")
print(dot_xy)


Dot product of v and w:
219
Dot product of x and v:
[29 77]
Dot product of x and y:
[[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [41]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_column = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)

print("Concatenate x and y along row:")
print(concat_xy_row)

print("Concatenate v and w along column:")
print(concat_vw_column)


Concatenate x and y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [42]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

try:
    concat_xv = np.concatenate((x, v), axis=1)
    print("Concatenate x and v:")
    print(concat_xv)
except ValueError as e:
    print(f"Error: {e}")


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


 In order to concatenate them along the columns, they must have the same number of rows.



**Problem - 4: Matrix Operations:**

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:

1. Prove A.A^−1 = I.

In [43]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)

print(result)


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.

In [44]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:")
print(AB)

print("BA:")
print(BA)


AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]


3. Prove (AB)^T = B^T * A^T

In [45]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB_T = np.transpose(np.dot(A, B))
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))

print("Transpose of AB:")
print(AB_T)

print("B^T * A^T:")
print(B_T_A_T)


Transpose of AB:
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1,
x − y + 2z = −3,
3x + y − z = 9

In [46]:
import numpy as np

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print(X)


[ 2.  1. -2.]


**10.2 Experiment: How Fast is Numpy?**

**1. Element-wise Addition:**

Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

In [47]:
import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000, 2000000)]

start_time = time.time()

result = [a + b for a, b in zip(list1, list2)]

end_time = time.time()

print("Time taken:", end_time - start_time)


Time taken: 0.2980220317840576


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [48]:
import numpy as np
import time

array1 = np.arange(1000000)
array2 = np.arange(1000000, 2000000)

start_time = time.time()

result_np = array1 + array2

end_time = time.time()

print("Time taken:", end_time - start_time)


Time taken: 0.014177799224853516


**Element-wise Multiplication**

Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

In [49]:
import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000, 2000000)]

start_time = time.time()

result_mul = [a * b for a, b in zip(list1, list2)]

end_time = time.time()

print("Time taken for element-wise multiplication:", end_time - start_time)


Time taken for element-wise multiplication: 0.1319880485534668


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [51]:
import numpy as np
import time

list1 = np.arange(1000000)
list2 = np.arange(1000000, 2000000)

start_time = time.time()

result_mul = list1 * list2

end_time = time.time()

print("Time taken for element-wise multiplication:", end_time - start_time)


Time taken for element-wise multiplication: 0.017601728439331055


**3. Dot Product**

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

In [52]:
import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()

dot_product = sum(a * b for a, b in zip(list1, list2))

end_time = time.time()

print("Time taken for dot product:", end_time - start_time)


Time taken for dot product: 0.08191609382629395


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [53]:
import numpy as np
import time

list1 = np.arange(1000000)
list2 = np.arange(1000000)

start_time = time.time()

dot_product = np.dot(list1, list2)

end_time = time.time()

print("Time taken for dot product:", end_time - start_time)


Time taken for dot product: 0.0021042823791503906


**4. Matrix Multiplication**

Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [54]:
import time

matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]

start_time = time.time()

result = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]

end_time = time.time()

print("Time taken for matrix multiplication:", end_time - start_time)


Time taken for matrix multiplication: 196.5520122051239


Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [55]:
import numpy as np
import time

matrix1 = np.random.rand(1000, 1000)
matrix2 = np.random.rand(1000, 1000)

start_time = time.time()

result = np.dot(matrix1, matrix2)

end_time = time.time()

print("Time taken for matrix multiplication:", end_time - start_time)


Time taken for matrix multiplication: 0.1375439167022705
